version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      ALLINIX_PLATFORM_HOST: 0.0.0.0
      ALLINIX_PLATFORM_DB_HOST: allinix_db
      ALLINIX_PLATFORM_DB_PORT: "3307"
      ALLINIX_PLATFORM_DB_USER: "allinix_platform"
      ALLINIX_PLATFORM_DB_PASS: "allinix_platform"
      ALLINIX_PLATFORM_DB_BASE: "allinix_platform"
    depends_on:
      - allinix_db

  allinix_db:
    image: mysql:8.0
    container_name: allinix_db
    restart: always
    build:
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "allinix_platform"
      MYSQL_USER: "allinix_platform"
      MYSQL_PASSWORD: "allinix_platform"
      MYSQL_ROOT_PASSWORD: "allinix_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - allinix_db:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

volumes:
  allinix_db:
